### PR TITLE
Rename handlers

### LINKED ISSUE #35: Rename handlers
See https://github.com/nielslange/smntcs-quantity-buttons-for-woocommerce/pull/31

### PR DESCRIPTION
**Pull request by im-mortal**
When I tried to dequeue the plugin js file, I found that the handler for it was `custom-script`, which wasn't very descriptive, not to mention that handler was already in use during theme development. 
I've changed handlers for both `custom-script` -> `smntcswcqb-script` and `custom-style` -> `smntcswcqb-style`, along with renaming `custom.js` and `custom.css` files to something meaningful (hopefully).

### CODE REVIEW

**Comment by nielslange** [comment]
Hello @im-mortal 👋 Sorry for my late reply and thank you so much for your contribution. I just merged your PR and will deploy a new version of the plug later today. If you give me your WordPress.org username, I'm happy to add you as a contributor to the plugin. 😉

**Comment by im-mortal** [comment]
Hey @nielslange, 
Thank you for merging my PR and, of course, the plugin. (it's amazing!)
The contribution is rather irrelevant, but if it's desirable to list all the contributors, I'm `@imm0rtal` at WordPress.org.
Thank you again and looking forward to seeing Quantity Buttons evolving!

**Comment by nielslange** [comment]
Hello @im-mortal 👋 

> Thank you for merging my PR and, of course, the plugin. (it's amazing!)

I'm glad to hear that!

> The contribution is rather irrelevant, but if it's desirable to list all the contributors, I'm @imm0rtal at WordPress.org.

To me, it's a sign of appreciation. And this is how your WordPress.org profile page looked before and after. You are now officially a plugin developer/contributor! 🙌

<table>
<tr>
<td>Before:
<br><br>

ORG-before
</td>
<td>After:
<br><br>

ORG-after
</td>
</tr>
</table>

**Comment by im-mortal** [comment]
Thank you! That means a lot to me! 🎉
Stay safe!

**Comment by nielslange** [comment]
I'm glad to hear that and please stay safe as well! 🙏

**Pull request merged**
